### ISSUE TITLE
Error in documentation (gulp command wrong!)

### ISSUE THREAD

**Issue by LarsGMortensen** [creativetimofficial/ct-material-dashboard-pro#189]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I would expect that when I check your documentation: The listed gulp-commands would be right.

# Current Behavior

The gulp-command for compiling the CSS is wrong.
It says "gulp compile:scss" when it should say "gulp compile-scss"
Please see attached screendump.

![error-gulp-command-documentation](https://user-images.githubusercontent.com/26773745/45242494-8cdd2b00-b2f0-11e8-8125-ef649bc602be.PNG)

**Comment by groovemen** [comment]
Hello @LarsGMortensen, 

Thank you for using our products and for this feedback, we will fix this issue ASAP. 
All the best, 
Stefan

**Comment by edwardtilley** [comment]
getting a ton of errors on gulp compile and gulp serve

I went to the trouble of ensuring I was running gulp v4.0.0 on Windows by using these commands per https://hackersandslackers.com/upgrading-to-gulp-4/
npm install gulp-cli -g
npm install gulp@4.0.0 -D

here are the errors:

gulp compile-scss
assert.js:374
    throw err;
    ^
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (F:\Users\etilley\Projects\MaterialPRO\material-dashboard-pro-html-v2.1.0\node_modules\←[4mundertaker←[24m\lib\set-task.js:10:3)
    at Gulp.task (F:\Users\etilley\Projects\MaterialPRO\material-dashboard-pro-html-v2.1.0\node_modules\←[4mundertaker←[24m\lib\task.js:13:8)
    at Object.<anonymous> (F:\Users\etilley\Projects\MaterialPRO\material-dashboard-pro-html-v2.1.0\gulpfile.js:34:6)
←[90m    at Module._compile (internal/modules/cjs/loader.js:955:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:811:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:723:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:848:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:74:18)←[39m
    at execute (C:\Users\etilley\AppData\Roaming\npm\node_modules\←[4mgulp-cli←[24m\lib\versioned\^4.0.0\index.js:36:18) {
  generatedMessage: ←[33mfalse←[39m,
  code: ←[32m'ERR_ASSERTION'←[39m,
  actual: ←[33mfalse←[39m,
  expected: ←[33mtrue←[39m,
  operator: ←[32m'=='←[39m
}
