### ISSUE TITLE
flatmap-stream@0.1.2

### ISSUE THREAD

**Issue by DamienBriggs** [creativetimofficial/ct-material-dashboard-pro#210]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [I downloaded the free version of material dashboard react about one week ago. I then purchased the pro version. I am still using the free version but with the login page carried over from pro ] I am running the latest version
- [Scanned for flatmap - saw nothing] I checked the documentation and found no answer
- [Yes ] I checked to make sure that this issue has not already been filed
- [Yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
I was trying to deploy to Heroku but the deployment crashed with a reference to flatmap-stream@0.1.2. I tried removing node_modules and then did npm install. 
I expected npm install to work without errors. I was deploying to Heroku and I expected it to end correctly. 

Please describe the behavior you are expecting
npm install produces this error:
npm ERR! code E404
npm ERR! 404 Not Found: flatmap-stream@0.1.2

I thought this might be something I had added so I went back to the directory I downloaded on Friday 23rd - Black Friday. I had this on my Mac and I hadn't amended it in any way. I deleted the node_modules directory and tried npm install. The same error occurred with the original code. npm ERR! 404 Not Found: flatmap-stream@0.1.2

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

**You may be interested to see this info:**
https://github.com/dominictarr/event-stream/issues/116

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
remove node_modules
npm install
You will get this error:
npm ERR! code E404
npm ERR! 404 Not Found: flatmap-stream@0.1.2

## Context
Within package-lock.json I found that flatmap-stream is a dependency of event-stream
"event-stream": {
      "version": "3.3.6",
      "resolved": "https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz",
      "integrity": "sha512-dGXNg4F/FgVzlApjzItL+7naHutA3fDqbV/zAZqDDlXTjiMnQmZKu+prImWKszeBM5UQeGvAl3u1wBiKeDh61g==",
      "requires": {
        "duplexer": "^0.1.1",
        "flatmap-stream": "^0.1.0",
        "from": "^0.1.7",
        "map-stream": "0.0.7",
        "pause-stream": "^0.0.11",
        "split": "^1.0.1",
        "stream-combiner": "^0.2.2",
        "through": "^2.3.8"
      }
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: iMac
* Operating System: 10.14.1
* Browser and Version: Chrome Version 70.0.3538.110 (Official Build) (64-bit)

## Failure Logs

Please include any relevant log snippets or files here.
This applies to both npm install and can also be seen when trying to deploy to Heroku:
21925 verbose type Error
21926 verbose stack Error: 404 Not Found: flatmap-stream@0.1.2
21926 verbose stack     at fetch.then.res (/Users/damien/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
21926 verbose stack     at tryCatcher (/Users/damien/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
21926 verbose stack     at Promise._settlePromiseFromHandler (/Users/damien/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
21926 verbose stack     at Promise._settlePromise (/Users/damien/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
21926 verbose stack     at Promise._settlePromise0 (/Users/damien/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
21926 verbose stack     at Promise._settlePromises (/Users/damien/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
21926 verbose stack     at Async._drainQueue (/Users/damien/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
21926 verbose stack     at Async._drainQueues (/Users/damien/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
21926 verbose stack     at Immediate.Async.drainQueues (/Users/damien/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
21926 verbose stack     at runCallback (timers.js:810:20)
21926 verbose stack     at tryOnImmediate (timers.js:768:5)
21926 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
21927 verbose cwd /Users/damien/planbig-dashboard/server/client
21928 verbose Darwin 18.2.0
21929 verbose argv "/Users/damien/.nvm/versions/node/v8.12.0/bin/node" "/Users/damien/.nvm/versions/node/v8.12.0/bin/npm" "install"
21930 verbose node v8.12.0
21931 verbose npm  v6.4.1
21932 error code E404
21933 error 404 Not Found: flatmap-stream@0.1.2

**Comment by DamienBriggs** [comment]
Just an update on this for people who may be experiencing the same issue:

The problem does seem to be a genuine attempt to add malicious code into a dependency, as outlined in  dominictarr/event-stream#116

I resolved the issue that I reported as follows: 

I used the following command to determine which global packages were installed.

> npm list -g --depth 0  

I then went through these and deleted and reinstalled each one. For example with create-react-app:

> npm uninstall -g create-react-app
> npm install -g create-react-app

In the directory containing the downloaded software from Creative Tim, I deleted node_modules and reinstalled them, but this did not rectify the issue. 

I then installed the latest version of event-stream:
> npm install --save event-stream     (though I could have just added it to package.json)

I then removed the node_modules directory:

> rm -rf node_modules

And reinstalled it: 

> npm install 

This appears to have resolved the issue.
